pipeline:
  # restore the cache from an sftp server
  restore_cache:
    image: appleboy/drone-sftp-cache
    restore: true
    mount: [ .glide, vendor ]
    ignore_branch: true

  build:
    image: appleboy/golang-testing:${GO_VERSION}
    environment:
      - GOPATH=/go
    commands:
      - make install
      - coverage all

  line:
    image: appleboy/drone-line
    pull: true
    to: u359650f919427b5229330c7205c47ee4
    when:
      status: [ success, failure ]
      matrix:
        GO_VERSION: 1.7.1

  gtalk:
    image: appleboy/drone-gtalk
    pull: true
    to: appleboy.tw@gmail.com
    when:
      status: [ success, failure ]
      matrix:
        GO_VERSION: 1.7.1

  facebook:
    image: appleboy/drone-facebook
    pull: true
    to: 1234973386524610
    when:
      status: [ success, failure ]
      matrix:
        GO_VERSION: 1.7.1

  # rebuild the cache on the sftp server
  rebuild_cache:
    image: appleboy/drone-sftp-cache
    rebuild: true
    mount: [ .glide, vendor ]
    ignore_branch: true
    when:
      branch: master
      matrix:
        GO_VERSION: 1.7.1

services:
  redis:
    image: redis:alpine

workspace:
  path: /go/src/github.com/appleboy/gorush

matrix:
  GO_VERSION:
    - 1.7.1
    - 1.6.3
