version: '3.5'

services:
  gorush:
    image: appleboy/gorush
    restart: always
    ports:
      - "8088:8088"
    expose:
      - "8088"
      - "9000"
    logging:
      options:
        max-size: "100k"
        max-file: "3"
    environment:
      - GORUSH_CORE_QUEUE_NUM=512
    networks:
      - vibik_shared_network

networks:
  vibik_shared_network:
    external: true
    name: vibik_shared_network
