FROM alpine

MAINTAINER Bo-Yi Wu <appleboy.tw@gmail.com>

RUN apk update && apk upgrade \
  && apk add ca-certificates \
  && rm -rf /var/cache/apk/*

RUN mkdir /app
ADD gorush.tar.gz /app/
ADD config/config.yml /app/config/
WORKDIR /app
ENTRYPOINT ["./gorush", "-c", "config/config.yml"]
EXPOSE 8088
