FROM appleboy/golang-testing

MAINTAINER Bo-Yi Wu <appleboy.tw@gmail.com>

ENV VERSION #VERSION#
RUN mkdir -p $GOPATH/src/github.com/appleboy/gorush
Add build.tar.gz $GOPATH/src/github.com/appleboy/gorush/
WORKDIR $GOPATH/src/github.com/appleboy/gorush
RUN make install
RUN CGO_ENABLED=0 make build_static

CMD tar -C bin -czf - gorush
