name: Run Lint and Testing

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '^1'
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: check documentation
        run : make embedmd

      - name: check golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --verbose

      - uses: hadolint/hadolint-action@v3.1.0
        name: hadolint for Dockerfile
        with:
          dockerfile: docker/Dockerfile

  testing:
    runs-on: ubuntu-latest
    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '^1'
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: testing
        env:
          ANDROID_API_KEY: ${{ secrets.ANDROID_API_KEY }}
          ANDROID_TEST_TOKEN: ${{ secrets.ANDROID_TEST_TOKEN }}
        run : make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          flags: ${{ matrix.os }},go-${{ matrix.go }}
