apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Chart.Name }}
data:
  # stat
  stats:
    engine: {{ .Values.stat.engine }}
    {{- if .Values.redis.enabled }}
    redis:
      host: {{ .Values.redis.host }}:{{ .Values.redis.port }}
    {{- end }}
